### ISSUE TITLE
Get rid of backend component

### ISSUE THREAD

**Issue by fidley** [lukas-mb/ABAP-SQL-Beautifier-Backend#1]
Hi @lukas-mb , 

I think, that it may be possible to get rid of the backend component, if you use it only for pretty print. To do that, on frontend side you would need to :

1. After update of the SQL statement,  you would need to select the statement programically.
2. Call Pretty Print Block command (ID com.sap.adt.tools.abapsource.ui.prettyPrintBlock)

I think it would work, but haven't tried it yet. I will need to test is also for ABAP Quick Fixes, so maybe I'll be faster than you in discovering it ;)

**Comment by lukas-mb** [comment]
Hi @fidley,

yes, that would be great, thanks for the tip! I remember I already did some research on this but got no results other than calling a FM. If I get some time, I'll definitely try this out :)

**Comment by fidley** [comment]
I couldn't stop myself from checking ;)

I had to create own inmplementation of ICompletionProposal (copy of CompletionProposal with small adaptation of APPLY function to call the pretty print after the replacement is done. A bit dirtly still, but it's working :) I will add this to quick fixes but need to prepare all places, where this should be called and I need to add preference as well.


	@Override
	public void apply(IDocument document) {
		try {
			document.replace(fReplacementOffset, fReplacementLength, fReplacementString);
			callPrettyPrintOfBlock(document);

		} catch (BadLocationException x) {
			// ignore
		}
	}

	private void callPrettyPrintOfBlock(IDocument document) {
		if (fcallPrettyPrintForBlock) {
			try {
				IEditorPart activeEditor = PlatformUI.getWorkbench().getActiveWorkbenchWindow().getActivePage()
						.getActiveEditor();
				IAbapSourcePage aSP = getTextEditor(activeEditor);
				TextSelection tS = new TextSelection(document, fReplacementOffset, fReplacementLength);
				aSP.getSelectionProvider().setSelection(tS);
				IHandlerService handlerService = PlatformUI.getWorkbench().getService(IHandlerService.class);
				try {
					handlerService.executeCommand("com.sap.adt.tools.abapsource.ui.prettyPrintBlock", null);
				} catch (ExecutionException | NotDefinedException | NotEnabledException | NotHandledException e) {
					e.printStackTrace();
				}
			} catch (Exception e) {
				e.printStackTrace();
			}

		}
	}

	public IAbapSourcePage getTextEditor(IEditorPart editor) {
		IAbapSourcePage textEditor = null;
		if (editor instanceof MultiPageEditorPart) {
			MultiPageEditorPart multiPageEditor = (MultiPageEditorPart) editor;
			IEditorPart activePage = (IEditorPart) multiPageEditor.getSelectedPage();
			if (activePage instanceof IAbapSourcePage) {
				textEditor = (IAbapSourcePage) activePage;
			} else if (multiPageEditor instanceof IAdtFormEditor) {

				IEditorPart ed = ((IAdtFormEditor) multiPageEditor).getActiveEditor();
				if (ed instanceof IAbapSourcePage) {
					textEditor = (IAbapSourcePage) ed;
				}
			}
		} else if (editor instanceof IAbapSourcePage) {
			textEditor = (IAbapSourcePage) editor;
		}
		return textEditor;
	}

**Comment by lukas-mb** [comment]
Haha I know this feeling :D

Really cool, thank you very much for sharing!

**Comment by lukas-mb** [comment]
Hi @fidley, thank you very much again. The plugin is now working without backend, awesome!!

**Comment by fidley** [comment]
There was small bug in the code, with the length of selection. I hope you found it 😁
